### ISSUE TITLE
Face area threshold not working correctly

### ISSUE THREAD

**Issue by rmcdermo** [firetools/blenderfds#11]
Emanuele, in your email you said that the face area threshold was 1E-6 BU (inches in this case).  But the smallest triangle in this cylinder is area = 4*math.pi*(0.0625)**2 / 11 = 0.00446 sq in.  I go back thinking that something is wrong with your English units.  Simple case is attached.

[Pilot_Section.blend.txt](https://github.com/firetools/blenderfds/files/2162843/Pilot_Section.blend.txt)

**Comment by rmcdermo** [comment]
OK, couple of mistakes I made in my submission above: First, I used dia instead of radius for the 1/16" dia port.  The correct area is 0.00111 sq in.  Still should work.  Also, please note that the value of the dia in the attached blend file is a result of me playing with that number in order to find where the threshold actually lies in the current code.  In my application, a diameter of 1/16" without unit scale adjustment is what we need.  Thanks.

**Comment by rmcdermo** [comment]
We should also make this threshold a parameter in BlenderFDS so the user has control over it.  And when the "Too Small Face Area" error occurs, we should see what area Blender thinks it has compared to the threshold.  So, a little more information in the error trap would be good.

**Comment by emanuelegissi** [comment]
Solved in current master

**Comment by emanuelegissi** [comment]
The threshold is now a parameter.
