### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by RomanIva** [firetools/blenderfds#16]
In Blender there is a next  way of loading up a background image file: Add-Empty-Image. Then click the icon "Type of active data to display and edit" and load image. The goal of such a process is to have background image visible in the user perspective mode. In BlenderFDS there in no such an icon, so the image is visible only in Top or Bottom or other, not in user perspective.

**Comment by emanuelegissi** [comment]
You are probably using the simplified user interface that hides some of the Blender features.
Here is how to have the full interface:

1) Open File > User Preferences
2) Select the Add-ons panel
3) Search the BlenderFDS addon

![immagine](https://user-images.githubusercontent.com/11455203/44957767-08487200-aed6-11e8-9478-2c750966e399.png)

4) In Preferences deselect "Simplify User Interface", then click on *Save User Settings* at the bottom
5) Close and restart Blender.
6) Now you have the full original Blender interface with BlenderFDS additions.

As the BF simplified user interface is not working as well as I wanted, I will presumably remove it in the next release.
