### ISSUE TITLE
GEOM Issue - Mesh>Cylinder>Cap Fill Type "Nothing">Add Modifier>Solidify

### ISSUE THREAD

**Issue by jstebbi** [firetools/blenderfds#17]
1) Can you tell me if it is possible for Blender FDS to code with GEOM a solid made with the following method?
     - in Blender I used Add>Mesh>Cylinder>Cap Fill Type "Nothing" then Add Modifier>Solidify to create a hollow cylinder with a 1 mesh width (.005m)

2) The code gives the following error on FDS6.7.6-0-g5064c500c-release:

```
forrtl: severe (157): Program Exception - access violation
Image              PC                Routine            Line        Source
fds.exe            00007FF63F845E25  Unknown               Unknown  Unknown
fds.exe            00007FF63F876248  Unknown               Unknown  Unknown
fds.exe            00007FF63F872383  Unknown               Unknown  Unknown
fds.exe            00007FF63F826E5D  Unknown               Unknown  Unknown
fds.exe            00007FF63F8DA7C9  Unknown               Unknown  Unknown
fds.exe            00007FF63EFB47D7  MAIN__                    464  main.f90
fds.exe            00007FF63EF72F3E  Unknown               Unknown  Unknown
fds.exe            00007FF63F963D28  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFB72067C24  Unknown               Unknown  Unknown
ntdll.dll          00007FFB723ED721  Unknown               Unknown  Unknown
```

Find my code attached.

[Candle2_1GEOM.txt](https://github.com/firetools/blenderfds/files/7515812/Candle2_1GEOM.txt)

If there is an alternative way to make a hollow cylinder, let me know.

**Comment by emanuelegissi** [comment]
1. Yes it is.
2. The problem seems to be that your GEOMs are too close. I fixed your case by boolean addition, creating one only object. (Remove the .txt extension and open it in BlenderFDS.

[CandleCylinder2_1GEOM_oneonly.blend.txt](https://github.com/firetools/blenderfds/files/7520529/CandleCylinder2_1GEOM_oneonly.blend.txt)

**Comment by jstebbi** [comment]
This looks good, but I want the "Candle Cylinder" and the "Container Cylinder" to have different MATL ID.  It is supposed to model a "Paraffin Wax" properties "Candle Cylinder" bulk and a "Glass" properties "Container Cylinder" around the outside.  Is this possible?

**Comment by emanuelegissi** [comment]
Yes, of  course. You mean different SURFs, that will link to different MATLs.
Here it is.

[CandleCylinder2_1GEOM_oneonly_surfs.blend.txt](https://github.com/firetools/blenderfds/files/7520869/CandleCylinder2_1GEOM_oneonly_surfs.blend.txt)
