### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by Tihon1234** [firetools/blenderfds#19]
The problem is that when I try to export in fds format, it gives the following error, when importing everything is OK and in other formats it also exports normally
How can this be fixed?
![image](https://user-images.githubusercontent.com/98514067/151316761-c4d85612-4008-4f15-ac85-b45f941f08dc.png)
![image](https://user-images.githubusercontent.com/98514067/151316772-7f38ab08-288b-415f-b62b-60c76a6331ef.png)

**Comment by emanuelegissi** [comment]
Please, attach your fds and blend file and I will take a look.

Il giorno gio 27 gen 2022 alle ore 09:05 Tihon1234 ***@***.***>
ha scritto:

**Comment by uporersith** [comment]
I believe this issue is related to the new  blender 3.0. I believe found the solution, see issue 20.
