### ISSUE TITLE
Entry Point Not Found, when importing BlenderFDS into Blender

### ISSUE THREAD

**Issue by vlasischar** [firetools/blenderfds#29]
During startup of the Blender i get the error: 

Blender:blender.exe - Entry Point Not Found
"The procedure entry point fatbinaryctl could not be located in the dynamic link library C:\Windows\System32\nvopencl.dll."

**Blender 2.78 - BlenderFDS-v.4.3.0**

**Comment by emanuelegissi** [comment]
I never received such error. I can't reproduce it. Please, try on a
different win machine, and write exactly how to reproduce it.
Emanuele
