### ISSUE TITLE
Develop an evac module in your firetools project

### ISSUE THREAD

**Issue by godisreal** [firetools/blenderfds#30]
Excuse me.  Do you offer to host an evac module in your firetools project?  
Randy told me that you give a good offer, but I am not sure if Timo would like to move his module here.  Have you ever talked to Timo about your idea?
In addition I also have an evac module in python, which can also read in certain data in fds input files.  If you would like, I am glad to share it and integrate it in your firetool project.

**Comment by emanuelegissi** [comment]
Hi Peng,
I have spoken to Randy about this opportunity to split the EVAC project
from the FDS+EVAC bundle. It is becoming unmaintainable for them, but it is
very much used here in Europe.

I suggested porting the current EVAC codebase to Python (and numpy) to
lower the barrier to new contributors.
I was not aware of your efforts.

So I am very happy to offer the fire tools repository for joining forces on
this project.

I propose you to meet this week via a video call on Thursday 23 at 2pm
(CEST) on MS Teams. You could briefly demo your project and explain the
code to us, as a first step.

Would it be ok with you? Where are you based?

I am inviting Ruggero Poletto as well, an Italian colleague.

Best regards,
Emanuele

**Comment by godisreal** [comment]
Hi, Emanuele, 
Thanks for your invitation.  I would like to join your discussion.  I will try to join your video meeting, but I am not sure if I can make it today.  BTW, what platform is used for your video meeting?  I suppose it is based on certain software. Skype or any others?  
Very importantly, it seems that Randy, you and I all agree to outsource evac as an independent module, but what is Timo's opinion?  Randy and I has left a message for Timo on an open FDS issue, but Timo hasn't replied yet.  Timo's opinion is important because he is the author of the evac module.

**Comment by emanuelegissi** [comment]
Timo's opinion is very important, I agree.
Skype is ok with me. But not today anymore.
What about next week?

Please, let's continue this conversation on regular email.
My email is: emanuele.gissi@gmail.com

**Comment by godisreal** [comment]
Weekly meeting is fine, and it is good to have a regular discussion so that we can exchange opinons and update the information, but I'd rather not wait for another week.  I have been waiting for Timo's reply for weeks.  My English is not good.  So writing to you every one or two days will be more effecient than talking to you once a week, and that makes myself better understood.  BTW, I live in Beijing, China.  

So I guess Timo did not know your kindly offering to host evac in firetool project.  Why not also invite Timo to your weekly meeting? If he likes your offering, I will help to outsource evac from fds.  If he does not, I can offer to write another indepedent evac program in python.  In fact I have got a program in python, which is promising in the model and algorithm.  

Best Regards, 
Peng WANG
