### ISSUE TITLE
Crash when installing cloned version with Blender 3.1

### ISSUE THREAD

**Issue by rmcdermo** [firetools/blenderfds#35]
Hi Ema,
I was just updating my BlenderFDS after the new release.  I installed the latest Blender (3.1.2), created the `scripts/addons` directory and cloned your repo there.  When I went to Edit >> Preferences >> Addons and searched for "blenderfds" the import module came up and when I checked the box, I got this error (second window below).  I'm on macOS 12.4 Monterey.  Any ideas?

<img width="772" alt="Screen Shot 2022-05-30 at 8 09 47 AM" src="https://user-images.githubusercontent.com/4418497/170989634-daf47031-1232-4321-b049-a794e64f8306.png">

<img width="772" alt="Screen Shot 2022-05-30 at 8 10 17 AM" src="https://user-images.githubusercontent.com/4418497/170989656-3424d0e7-7846-4bcb-9c48-4c5feaa07a83.png">

**Comment by emanuelegissi** [comment]
Yes, sure.
As for the requirements, thou shall install Blender 3.2.0 beta. Not 3.1.x.
that was too buggy. I skipped it ;-)

**Comment by emanuelegissi** [comment]
Let me know if it works.

**Comment by emanuelegissi** [comment]
And if your BlenderFDS addon install folder is not called "blenderfds" you
should rename it "blenderfds".

This was a bug of the previous version.

Even better, delete your user configuration directory and reinstall the
addon from scratch.

**Comment by emanuelegissi** [comment]
Your user folder to be deleted should be something like this:
/Users/$USER/Library/Application Support/Blender/3.1/

**Comment by rmcdermo** [comment]
Ema,
I get the same with 3.2.  I have deleted 3.1

<img width="772" alt="Screen Shot 2022-05-30 at 10 02 54 AM" src="https://user-images.githubusercontent.com/4418497/171008408-b318f968-96c4-4c30-b28c-779932daa9b3.png">

I am cloning the add on per the instructions in the install [wiki](https://github.com/firetools/blenderfds/wiki/Install).  If these instructions are not up-to-date, please let me know.

**Comment by rmcdermo** [comment]
Here is my addons directory

<img width="1072" alt="Screen Shot 2022-05-30 at 10 11 31 AM" src="https://user-images.githubusercontent.com/4418497/171009845-6f9c993f-a7bb-4f97-a034-9e909ba3c1c1.png">

**Comment by emanuelegissi** [comment]
It seems to me that there is a leftover from your previous user
configuration.

May you please delete completely the blender user directory:
/Users/$USER/Library/Application Support/Blender

**Comment by emanuelegissi** [comment]
Another thing that you may check is that inside the blender directory
there's directly the code and not another blender directory.
This sometimes happens to me when I git clone

**Comment by rmcdermo** [comment]
I'm sorry, but I've deleted everything and reinstalled from scratch.  I get the same error.  I have installed the Intel beta version of Blender 3.2.0 from here.

<img width="1552" alt="Screen Shot 2022-05-30 at 12 31 36 PM" src="https://user-images.githubusercontent.com/4418497/171032370-5cfbccd6-5cf4-460b-94a2-5667b64d4070.png">

**Comment by rmcdermo** [comment]
I'll check with Marcos.  I think we need another macOS test.  He's probably fishing :)

**Comment by rmcdermo** [comment]
Ema,
An update.  @marcosvanella got something to work on Catalina, but he first put Blender.app into his User local and put `blenderfds` into the Blender.app.  I did this as well, and it worked.  But there is a catch.  On Monterey, you first have to open Blender.app so it can do the checksum and verify the program.  Then you can start adding stuff to `Blender.app/Contents/Resources/3.2/scripts/addons`.

I don't think this is the proper way.  Most users will simply copy Blender.app to their Applications directory.  So, it should work to put blenderfds into Application Support.  I will check with Marcos if he can do this method.

**Comment by marcosvanella** [comment]
In Catalina I installed Blender 3.2 in /Applications. Then I made this directory:
/Users/MYUSER/Library/Application Support/Blender/3.2/scripts/addons
Then
>>git clone git@github.com:firetools/blenderfds.git

Then went to 
/Users/MYUSER/Library/Application Support/Blender/3.2/config

>>rm *

opened Blender in applications, Preferences => click Import Export BlenderFDS => the in there load Default BlenderFDS settings. It worked. 
See if doing this helps, if not might be something related to Monterrey.
 
![Screen Shot 2022-06-01 at 8 46 35 AM](https://user-images.githubusercontent.com/7450069/171408088-3c1d5f87-f924-4af4-a3bc-0773e01043eb.png)

**Comment by emanuelegissi** [comment]
Perfect! Thank you so much Marcos.

Do you think I should update this page?
https://github.com/firetools/blenderfds/wiki/Install#install-a-development-version

**Comment by marcosvanella** [comment]
Ciao Ema, I think we can update the versions in there to 3.2 given that it is the actual development version. Let's see first if Randy can get it to work. I also have a laptop at home with Big Sur (a version less than Monterrey). I can try there.

**Comment by emanuelegissi** [comment]
Okay, right

**Comment by rmcdermo** [comment]
Well, sorry.  After all the trouble, the issue seems to have been simply that I had the Blender app open when I cloned the blenderfds repo.  If I close the app and reopen it, then the addon functions properly.  I updated the wiki notes.  As always, I am a good test monkey to make things idiot proof.

**Comment by emanuelegissi** [comment]
No problem is a silly problem ;-)

**Comment by emanuelegissi** [comment]
Ah, better!

In fact the addon should be installed in the user directory that should not
be checksummed, I suppose. The same that gets used by Blender when
installing a stable from the zip file.

Maybe, if you got spare time, you could try to discover for me where
Blender installs the userspace add-ons. According to the documentation it
should be something like:

/Users/$USER/Library/Application Support/Blender/3.2/

Thank you

**Comment by emanuelegissi** [comment]
Okay, I am sorry. In fact the MacOS version is tested only on a Catalina
virtual machine :-( not very realistic indeed
