### ISSUE TITLE
Cell Size in Different Units [Convenience]

### ISSUE THREAD

**Issue by TristanHehnen** [firetools/blenderfds#39]
Dear Emanuele,

in the object properties tab of the MESH the cell size is shown. However, the numbers are only given up to milimeter precision. I assume that is well sufficient when working with large scale simulation setups like buildings. In my work I'm having simulation setups that are regularily in the cm scale where cells are in the mm range. Would it be possible to have the unit change for these numbers? Maybe it could be associated with the definition in the Units section of the scene properties tab. However, if BlenderFDS could adapt it automatically would be more convenient, I guess. For examples in situations where multiple meshes are used to create some local refinement.

For example, cell size here would be around 1.66 mm:
![grafik](https://user-images.githubusercontent.com/34650649/174050773-65d5010f-4e28-4156-91bc-fc1fd4612613.png)

Best,
Tristan

**Comment by emanuelegissi** [comment]
You are right, this should be implemented.
Let me think how to do that automatically.

**Comment by emanuelegissi** [comment]
I did not find any simple way of doing that automatically.
So I added precision (significant decimal digits) configuration for all quantities to config.py
Please, test it and tell me if this works for you.
