### ISSUE TITLE
SURFs are Exported for Objects Excluded via the View Layer

### ISSUE THREAD

**Issue by TristanHehnen** [firetools/blenderfds#40]
Dear Emanuele,

when exporting the scene to an FDS input file, also SURF definitions are exported that belong to objects that are excluded from the view layer. From my perspective this is not an expected behaviour: if the object is in a collection that is not part of the active view layer it's SURF should also not be exported. 

Best,
Tristan

**Comment by emanuelegissi** [comment]
I cannot reproduce it with the current master version. Here is an example case that works
[view_layer_SURF_and_OBST.zip](https://github.com/firetools/blenderfds/files/8930849/view_layer_SURF_and_OBST.zip)
.
