### ISSUE TITLE
FDS Input File Export Options

### ISSUE THREAD

**Issue by TristanHehnen** [firetools/blenderfds#41]
Dear Emanuele,

it seems that the export options are missing in the export menu. In Blender 2.91.2 there were some options to control if all SURF should be exported or not, for example.

![grafik](https://user-images.githubusercontent.com/34650649/174305095-313076aa-e36a-4569-8f62-c290a8286124.png)

 I would also like to ask if another option could be added in order not to export any SURF at all.

Best, 
Tristan

**Comment by emanuelegissi** [comment]
Unfortunately, the wiki pages are not yet updated to the new version.

I removed that possibility because it was not very useful.
Now, only SURFs that are somehow referenced in the case are exported.
Do you see any application of that "export all SURFs" that I do not see?
