### ISSUE TITLE
File Name and CHID [Convenience] 

### ISSUE THREAD

**Issue by TristanHehnen** [firetools/blenderfds#42]
Dear Emanuele,

sometimes it would be nice to be able to have CHID different from the FDS input file names. Could there be an option, maybe a checkbox at either location 1 or 2, to control if the input file name should be equal the CHID? 
It is convenient for instance, when working in the terminal, it is handy to have CHID and file name different when one wants to remove all the files produced by FDS but keep the input file.

![grafik](https://user-images.githubusercontent.com/34650649/174307169-befcdb28-4079-4d12-ad79-7cf10a74f933.png)

Best,
Tristan

**Comment by emanuelegissi** [comment]
Well, this is quite hardcoded and difficult to change now. Now I want to release ASAP.
And it is quite easy to write an fds clean script that removes all the output files except the *.fds one.
If you see any other use case, I will implement that during the next release.
