### ISSUE TITLE
Improve mutual MESH alignment

### ISSUE THREAD

**Issue by emanuelegissi** [firetools/blenderfds#43]
I just uploaded an updated MESH alignment.
@rupole1185 When you have time, may you tell me what you think about it?

**Comment by rupole1185** [comment]
@emanuelegissi today I made some tests and to me the align mesh seemed to be working OK! I used that to make a mesh less refined and to re-allign several meshes one another and after that FDS was able to positively work! Great job!

**Comment by emanuelegissi** [comment]
Very good! Happy to know it's useful
