### ISSUE TITLE
Error: meta2: Bad geometry: Non manifold vertices detected (86 vertices)

### ISSUE THREAD

**Issue by rakyuv** [firetools/blenderfds#54]
Hi all,
I started using BlenderFDS only today, and I am stuck at converting obj to FDS GEOM or OBST. I'd prefer to use GEOM over OBST, for it creates a more continuous structure than the square/rectangular cylinders generated by OBST. 

This is the [Screenshot](https://github.com/user-attachments/assets/d563289a-1c1d-42e5-90e5-fc8ae4678c2d) of my problem. The error I get is:
Error: meta2: Bad geometry: Non manifold vertices detected (86 vertices) 

Could you please help me how to fix the issue ?

Thanks

**Comment by emanuelegissi** [comment]
This is not an issue, it is a... feature! 

Please, read this wiki page:
https://github.com/firetools/blenderfds/wiki/Geometries

and paragraph 7.3 of FDS User guide, in particular: 7.3.3 Triangulated Surfaces Quality
