### ISSUE TITLE
if a box come from dxf, i can't add fds attrubute for it

### ISSUE THREAD

**Issue by HouXinyv** [firetools/blenderfds#55]
i import a dxf file, this file contains a box. But i can't add fds attribute for it as the follow picture.
![image](https://github.com/user-attachments/assets/ae7c293b-53f1-4487-b9ef-91440b782f65)

if i select a box which is drawing by blender, i can add fds attribute for it as the follow picture. 
![image](https://github.com/user-attachments/assets/3f484b3d-fd89-4444-9597-9d6a2a046e6b)

**Comment by HouXinyv** [comment]
sorry！ i know the answer, blenderfds support mesh not curve.  when i import a dxf file, blender will use curve to draw it. so i need to transform curve to mesh. my operation as follow picture
![image](https://github.com/user-attachments/assets/b2641bc3-890c-4c43-9a10-ab753acfb27c)

**Comment by emanuelegissi** [comment]
Great job, let me know if it works for you.

Il mer 30 ott 2024, 05:21 HouXinyv ***@***.***> ha scritto:
