### ISSUE TITLE
FDS add-ons mancante

### ISSUE THREAD

**Issue by Giorgia230119** [firetools/blenderfds#6]
Salve,
Ho scaricato Blender ma non trovo tra gli add-ons FDS (il codice del quale sono alla ricerca di una GUI).
Grazie mille,
M.

**Comment by emanuelegissi** [comment]
Please, follow the instructions here:
https://github.com/firetools/blenderfds/wiki/Installing

**Comment by emanuelegissi** [comment]
It should be fixed now. The make_release.py script was not behaving as expected.
