### ISSUE TITLE
Install wiki for macOS with Blender 2.91

### ISSUE THREAD

**Issue by rmcdermo** [firetools/blenderfds#8]
Hi Emanuele,
Just installing the latest with 2.91 and trying use the github clone options.  What I noticed with the installation of 2.91 was that Blender did _not_ put a new directory in my `Library/Application Support/Blender/` folder.  It seems that with 2.91 you need to use
```
/Applications/Blender.app/Contents/Resources/2.91/scripts/addons/
```
Other than that, the instructions were spot on.  Thanks!

**Comment by emanuelegissi** [comment]
Hi Randy,
Rereading the Blender documentation, it seems to me that the
/Applications/Blender.app/Contents/Resources/2.91/scripts/addons/ path is
used for the distributed official addons.
The user's addons on macOS should be put in something like:
/Users/$USER/Library/Application
Support/Blender/2.92/script/addons/
This second directory should be always writable by the user, even without
administrative privileges.
Can you confirm that?
Thank you,
Ema

Il giorno lun 1 mar 2021 alle ore 18:10 Randy McDermott <
notifications@github.com> ha scritto:

**Comment by rmcdermo** [comment]
Ema,
Putting things in `~/Library/Application Support/Blender/2.92/scripts/addons/` works.  Since I have write access to the `/Applications` directory, I guess I had no problem with that.  There were two things that confused me before.  First, the 2.92 directory does not show up immediately it seems.  It seems like you need to make some kind of change to the user preferences before this shows up.  Second, even once it shows up, only a `~/Library/Application Support/Blender/2.92/config/` folder exists.  So, I created the `.../2.92/scripts/addons/` manually and then cloned the repo there and was able to import blenderfds from there.  I guess the point is that if you are doing a completely fresh install of both Blender and BlenderFDS, the details of the install may be somewhat confusing.  I am not sure if it would be better to just clone into `.../2.92/config/` ?  I did not try that.  I would just add a note that 2.9x will not show up until a user preference panel is opened and saved (that is automatic in 2.9x, so might need to make a dummy change).  Then if you don't already have other addons, you need to create the `.../2.92/scripts/addons/` directory before cloning or unzipping the zip file.  Cheers...

**Comment by emanuelegissi** [comment]
Ok, thanks.
I updated the wiki page with your information.
Maybe the 2.92 user dir appears only after the first Blender run.

> I am not sure if it would be better to just clone into .../2.92/config/
No, Blender is looking only into the addons folder, both the general and
the user ones.


Il giorno mar 2 mar 2021 alle ore 14:58 Randy McDermott <
notifications@github.com> ha scritto:

**Comment by rmcdermo** [comment]
All works fine with latest

**Comment by emanuelegissi** [comment]
Ok
