### ISSUE TITLE
Possible conflict with IfcOpenShell addon

### ISSUE THREAD

**Issue by TristanHehnen** [firetools/blenderfds#9]
Hi Emanuele,

I've tried to install the IfcOpenShell addon after having blenderfds installed. There seems to be a conflict between both addons when trying to register IfcOpenShell during install, when blenderfds is already installed. There is an issue open with IfcOpenShell on this as well:

https://github.com/IfcOpenShell/IfcOpenShell/issues/1446

I'll provide there a link this issue.

**Comment by emanuelegissi** [comment]
Please, see if something changes by removing the ui simplification in the
bf settings and restarting Blender.

**Comment by Moult** [comment]
Fantastic add-on! I'd love to have a close integration with BlenderFDS and BlenderBIM Add-on :) Is FDS only for large scale fire sim or can it be used for building-scale simulation?

**Comment by emanuelegissi** [comment]
Hi Dion, sorry I did not notice your comment until now.
The main FDS use is indeed fire simulation at building scale, so I am very
interested in a possible integration with BlenderBIM.
I propose a call on the subject. Where are you based? I am in Genoa, Italy.

Il giorno mer 5 mag 2021 alle ore 14:19 Dion Moult ***@***.***>
ha scritto:

**Comment by Moult** [comment]
I'm on the Sydney timezone in Australia. Would you mind posting on the osarch.org community forums at community.osarch.org with a proposed time and date to meet? That way it will reach a wider audience of AEC professionals working on open source projects and maybe others can join in and collaborate as well!

**Comment by emanuelegissi** [comment]
I fixed the compatibility issue with BlenderBIM. It was due to Blender UI simplification. Next release will have it.

**Comment by Moult** [comment]
Thanks so much!
