### ISSUE TITLE
UnicodeEncodeError: 'charmap' can't encode character '\xb2' in position XXX: character maps to <undefined>

### ISSUE THREAD

**Issue by PiPrus** [firetools/blenderfds#9]
Hi,

I struggle with a UnicodeEncodeError: 'charmap' can't encode character '\xb2' in position XXX: character maps to <undefined>. The '\xb2' is an equivalent to "superscript digit two".  I do use Blender 2.76b and BlenderFDS 4.0.6. 

First I thought, as I do not explicitly use superscrpited "2" anywhere in the input data (tanks.blend), I believed this must have something to do with the conflict between addon BlenderFDS and pure Blender code while exporting. Also, the pop-up error refers to cp1250.py decoding table that acctually doesn't include such a character at all. The superscripted "2" however exists in a few source files of add-on.

Now I'm not sure if this is true and if it's not a case specific problem, as I have no problem running new simpler case (f5.blend) basing on the same rules.

I do attach both cases (just rename txt to blend - for some reason I cannot upload zip here ;/ ).
[f5.txt](https://github.com/firetools/blenderfds/files/434535/f5.txt)
[tanks.txt](https://github.com/firetools/blenderfds/files/434536/tanks.txt)
![error](https://cloud.githubusercontent.com/assets/21217960/17928561/96eecbd4-69fb-11e6-8531-9f222b49c723.png)

Best Regards,
Piotr Prusiński, M.Sc. Eng.
---
Senior CFD Specialist
CFD Analysis Group (UZ3)
National Centre for Nuclear Research (NCBJ)
A. Sołtana 7, PL-05400 Otwock-Świerk
phone: +48.222731126

**Comment by emanuelegissi** [comment]
Well, I cannot reproduce the problem on Linux. It seems Windows specific.
I have an idea of what could be the problem, a little Blender bug on Windows.

In this version of your file I only deleted the "New SURF.002" Blender material:
[tanks.blend.zip](https://github.com/firetools/blenderfds/files/438186/tanks.blend.zip)

Please, try to open this file and export it to FDS. If it works, the bug is identified and will be shortly corrected.

Let me know.
Emanuele

**Comment by PiPrus** [comment]
Dear Emanuele,

You are entirely right, the issue was badly specified surface. The thing
is, I don't now how to delete it. The only way I could work around was to
change the name of this unfortune one for the moment. Could you tell me how
to get rid of it definitely?

Best regards,
Piotr

2016-08-26 0:39 GMT+02:00 Emanuele Gissi <notifications@github.com>:

**Comment by emanuelegissi** [comment]
Hi Piotr,
I am going to release BlenderFDS 4.1.0 very soon.
So, I worked on this issue.

I cannot reproduce the issue on Linux, this is specific to Windows.
But I think I found a solution, with ...your help.

Please, modify line 59 of the file zzz_blenderfds\utils.py:
`... with open(filepath,"w") as out_file: ...`
like this:
`... with open(filepath,"w",encoding="utf8",errors="ignore") as out_file: ...`

Does it work?
If it's ok I am going to include it in the next release.

Best regards,
Emanuele

**Comment by emanuelegissi** [comment]
You can directly try the new 4.1.0 release and enjoy its new features...
I wait for your confirmation before announcing it on the discussion groups.
Emanuele
